# Generated by Django 6.0.5 on 2026-05-14 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.TextField()),
                ('full_text', models.TextField()),
                ('markdown_content', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('headings', models.JSONField(default=list)),
                ('faq_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('serp_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serp.serpresult')),
            ],
        ),
    ]
