# Generated by Django 5.0.14 on 2026-05-15 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_alter_keyword_id'),
        ('serp', '0002_alter_contentembedding_id_alter_serpresult_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PAAQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paa_questions', to='keywords.keyword')),
            ],
        ),
    ]
