# Generated by Django 5.0.14 on 2026-05-15 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_alter_keyword_id'),
        ('serp', '0003_paaquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('level', models.CharField(default='INFO', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='keywords.keyword')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
