# Generated by Django 6.0.5 on 2026-05-14 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnalysisReport',
        ),
    ]
